# Elastic Search Variables
elasticsearch_host: localhost
systemd_src: elastic-timeout.conf

# Kibana Variables
kibana_host: localhost

# Logstash Variables
logstash_conf: logstash.conf

# Nagios Variables
nagios_user: nagiosadmin
nagios_password: password

# LAMP Variables
domain: kateaggabao-tip
owner: kateaggabao-tip
group: kateaggabao-tip
index_html: index.html
ubuntu_src: kateaggabao-tip-ubuntu.conf
centos_src: katespade-tip-centos.conf
